---
title: "analysis"
output: html_document
date: "2024-11-11"
---

```{r}
library(dplyr)
library(ggplot2)
library(reshape2)
```

```{r}
am<-read.csv("CMMmm.csv",as.is=TRUE)
```

```{r}
#create CS variable & find indices
am.indices <- am
am.indices$CS <- (am.indices$CL + am.indices$CWB)/2

am.indices <- am.indices %>%
  mutate(across(where(is.numeric) & !matches("CS"), ~ . / CS))
```

```{r}
#fit regression (Y/CS)~CS for each variable & store coefficients
coefficient.list <- list()

for (i in 5:23) {
  # Fit the regression model
  model <- lm(am.indices[[i]] ~ am.indices[[24]])
  
  #store coefficients
  model_coeffs <- coef(model)
  
  coefficient.list[[colnames(am.indices)[i]]] <- model_coeffs

}  

coefficient.df <- as.data.frame(do.call(rbind, coefficient.list))
colnames(coefficient.df) <- c("Intercept", "Slope")

coefficient.df
```

```{r}
a <- coefficient.df$Slope
b <- coefficient.df$Intercept
CS.s <- mean(am.indices$CS)

am.D <- data.frame(matrix(ncol = 19, nrow = 425))
for (i in 1:19){
  am.D[i] <- a[i]*am.indices$CS + b[i]
}

am.C.cal <- data.frame(matrix(ncol = 19, nrow = 1))
for (i in 1:19){
  am.C.cal[i] <- a[i]*CS.s + b[i]*CS.s
}
```

```{r}
am.I.css <- data.frame(matrix(ncol = 19, nrow = 425))
for (i in 1:19){
  am.I.css[i] <- am.indices[,4+i] / am.D[[i]] * am.C.cal[[i]]
}

colnames(am.I.css) <- colnames(am.indices)[5:23]
am.I.css$CS <- am.indices$CS
colnames(am.I.css) <- c(colnames(am.indices)[5:23], "CS")
```

```{r}
am$CS <- (am$CL + am$CWB)/2
am.long <- melt(am, id.vars = "CS", measure.vars = names(am)[5:23])

# Plot using ggplot2 with facet_wrap
ggplot(am.long, aes(x = CS, y = value)) +
  geom_point(alpha = 0.6) +
  facet_wrap(~ variable, scales = "free_y") +
  labs(x = "CS", y = "Value") +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 8),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

```{r}
am.indices.long <- melt(am.indices, id.vars = "CS", measure.vars = names(am.indices)[5:23])

# Plot using ggplot2 with facet_wrap
ggplot(am.indices.long, aes(x = CS, y = value)) +
  geom_point(alpha = 0.6) +
  facet_wrap(~ variable, scales = "free_y") +
  labs(x = "CS", y = "Value") +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 8),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

```{r}
am.indices.b <- am.indices %>%
  filter(sp == "batesii")
am.indices.b.long <- melt(am.indices.b, id.vars = "CS", measure.vars = names(am.indices.b)[5:23])

# Plot using ggplot2 with facet_wrap
ggplot(am.indices.b.long, aes(x = CS, y = value)) +
  geom_point(alpha = 0.6) +
  facet_wrap(~ variable, scales = "free_y") +
  labs(x = "CS", y = "Value") +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 8),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

```{r}
am.indices.b <- am.indices %>%
  filter(sp == "heteroclitus")
am.indices.b.long <- melt(am.indices.b, id.vars = "CS", measure.vars = names(am.indices.b)[5:23])

# Plot using ggplot2 with facet_wrap
ggplot(am.indices.b.long, aes(x = CS, y = value)) +
  geom_point(alpha = 0.6) +
  facet_wrap(~ variable, scales = "free_y") +
  labs(x = "CS", y = "Value") +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 8),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

```{r}
am.indices.b <- am.indices %>%
  filter(sp == "hildebrandti")
am.indices.b.long <- melt(am.indices.b, id.vars = "CS", measure.vars = names(am.indices.b)[5:23])

# Plot using ggplot2 with facet_wrap
ggplot(am.indices.b.long, aes(x = CS, y = value)) +
  geom_point(alpha = 0.6) +
  facet_wrap(~ variable, scales = "free_y") +
  labs(x = "CS", y = "Value") +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 8),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```